import type { ComponentType } from 'react';

/**
 * Реєстр контенту тем. Динамічний import з літеральним шляхом — тому MDX
 * потрапляє у збірку і не залежить від файлової системи в рантаймі
 * (важливо для standalone-образу на Cloud Run).
 *
 * Кожен розділ — окремий файл і окрема сторінка. Вигляд «усе одним полотном»
 * складається з тих самих файлів, тому другого джерела правди немає.
 */
type ContentLoader = () => Promise<{ default: ComponentType }>;

export const SECTION_CONTENT: Record<string, Record<string, ContentLoader>> = {
  'past-tenses': {
    idea: () => import('@/content/topics/past-tenses/sections/idea.mdx'),
    'past-simple': () => import('@/content/topics/past-tenses/sections/past-simple.mdx'),
    'past-continuous': () => import('@/content/topics/past-tenses/sections/past-continuous.mdx'),
    'past-perfect': () => import('@/content/topics/past-tenses/sections/past-perfect.mdx'),
    markers: () => import('@/content/topics/past-tenses/sections/markers.mdx'),
    comparison: () => import('@/content/topics/past-tenses/sections/comparison.mdx'),
    stories: () => import('@/content/topics/past-tenses/sections/stories.mdx'),
    translation: () => import('@/content/topics/past-tenses/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/past-tenses/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/past-tenses/sections/decision.mdx'),
    exercises: () => import('@/content/topics/past-tenses/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/past-tenses/sections/quiz.mdx'),
    history: () => import('@/content/topics/past-tenses/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/past-tenses/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/past-tenses/sections/plan.mdx'),
  },
  'present-tenses': {
    idea: () => import('@/content/topics/present-tenses/sections/idea.mdx'),
    'present-simple': () => import('@/content/topics/present-tenses/sections/present-simple.mdx'),
    'present-continuous': () =>
      import('@/content/topics/present-tenses/sections/present-continuous.mdx'),
    'present-perfect': () => import('@/content/topics/present-tenses/sections/present-perfect.mdx'),
    'perfect-vs-past': () => import('@/content/topics/present-tenses/sections/perfect-vs-past.mdx'),
    markers: () => import('@/content/topics/present-tenses/sections/markers.mdx'),
    comparison: () => import('@/content/topics/present-tenses/sections/comparison.mdx'),
    future: () => import('@/content/topics/present-tenses/sections/future.mdx'),
    stories: () => import('@/content/topics/present-tenses/sections/stories.mdx'),
    translation: () => import('@/content/topics/present-tenses/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/present-tenses/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/present-tenses/sections/decision.mdx'),
    exercises: () => import('@/content/topics/present-tenses/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/present-tenses/sections/quiz.mdx'),
    history: () => import('@/content/topics/present-tenses/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/present-tenses/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/present-tenses/sections/plan.mdx'),
  },
  'future-tenses': {
    idea: () => import('@/content/topics/future-tenses/sections/idea.mdx'),
    will: () => import('@/content/topics/future-tenses/sections/will.mdx'),
    'going-to': () => import('@/content/topics/future-tenses/sections/going-to.mdx'),
    'will-vs-going-to': () =>
      import('@/content/topics/future-tenses/sections/will-vs-going-to.mdx'),
    'present-forms': () => import('@/content/topics/future-tenses/sections/present-forms.mdx'),
    'future-continuous': () =>
      import('@/content/topics/future-tenses/sections/future-continuous.mdx'),
    'future-perfect': () => import('@/content/topics/future-tenses/sections/future-perfect.mdx'),
    markers: () => import('@/content/topics/future-tenses/sections/markers.mdx'),
    comparison: () => import('@/content/topics/future-tenses/sections/comparison.mdx'),
    highlight: () => import('@/content/topics/future-tenses/sections/highlight.mdx'),
    stories: () => import('@/content/topics/future-tenses/sections/stories.mdx'),
    translation: () => import('@/content/topics/future-tenses/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/future-tenses/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/future-tenses/sections/decision.mdx'),
    exercises: () => import('@/content/topics/future-tenses/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/future-tenses/sections/quiz.mdx'),
    history: () => import('@/content/topics/future-tenses/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/future-tenses/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/future-tenses/sections/plan.mdx'),
  },
  'sentence-structure': {
    idea: () => import('@/content/topics/sentence-structure/sections/idea.mdx'),
    statement: () => import('@/content/topics/sentence-structure/sections/statement.mdx'),
    questions: () => import('@/content/topics/sentence-structure/sections/questions.mdx'),
    negatives: () => import('@/content/topics/sentence-structure/sections/negatives.mdx'),
    adverbs: () => import('@/content/topics/sentence-structure/sections/adverbs.mdx'),
    adjectives: () => import('@/content/topics/sentence-structure/sections/adjectives.mdx'),
    objects: () => import('@/content/topics/sentence-structure/sections/objects.mdx'),
    'dummy-subjects': () =>
      import('@/content/topics/sentence-structure/sections/dummy-subjects.mdx'),
    emphasis: () => import('@/content/topics/sentence-structure/sections/emphasis.mdx'),
    stories: () => import('@/content/topics/sentence-structure/sections/stories.mdx'),
    translation: () => import('@/content/topics/sentence-structure/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/sentence-structure/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/sentence-structure/sections/decision.mdx'),
    exercises: () => import('@/content/topics/sentence-structure/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/sentence-structure/sections/quiz.mdx'),
    history: () => import('@/content/topics/sentence-structure/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/sentence-structure/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/sentence-structure/sections/plan.mdx'),
  },
  conditionals: {
    idea: () => import('@/content/topics/conditionals/sections/idea.mdx'),
    zero: () => import('@/content/topics/conditionals/sections/zero.mdx'),
    first: () => import('@/content/topics/conditionals/sections/first.mdx'),
    second: () => import('@/content/topics/conditionals/sections/second.mdx'),
    third: () => import('@/content/topics/conditionals/sections/third.mdx'),
    mixed: () => import('@/content/topics/conditionals/sections/mixed.mdx'),
    unless: () => import('@/content/topics/conditionals/sections/unless.mdx'),
    wishes: () => import('@/content/topics/conditionals/sections/wishes.mdx'),
    comparison: () => import('@/content/topics/conditionals/sections/comparison.mdx'),
    stories: () => import('@/content/topics/conditionals/sections/stories.mdx'),
    translation: () => import('@/content/topics/conditionals/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/conditionals/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/conditionals/sections/decision.mdx'),
    exercises: () => import('@/content/topics/conditionals/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/conditionals/sections/quiz.mdx'),
    history: () => import('@/content/topics/conditionals/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/conditionals/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/conditionals/sections/plan.mdx'),
  },
  modals: {
    idea: () => import('@/content/topics/modals/sections/idea.mdx'),
    ability: () => import('@/content/topics/modals/sections/ability.mdx'),
    permission: () => import('@/content/topics/modals/sections/permission.mdx'),
    obligation: () => import('@/content/topics/modals/sections/obligation.mdx'),
    advice: () => import('@/content/topics/modals/sections/advice.mdx'),
    probability: () => import('@/content/topics/modals/sections/probability.mdx'),
    'past-modals': () => import('@/content/topics/modals/sections/past-modals.mdx'),
    'will-would': () => import('@/content/topics/modals/sections/will-would.mdx'),
    comparison: () => import('@/content/topics/modals/sections/comparison.mdx'),
    stories: () => import('@/content/topics/modals/sections/stories.mdx'),
    translation: () => import('@/content/topics/modals/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/modals/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/modals/sections/decision.mdx'),
    exercises: () => import('@/content/topics/modals/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/modals/sections/quiz.mdx'),
    history: () => import('@/content/topics/modals/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/modals/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/modals/sections/plan.mdx'),
  },
  articles: {
    idea: () => import('@/content/topics/articles/sections/idea.mdx'),
    'a-an': () => import('@/content/topics/articles/sections/a-an.mdx'),
    the: () => import('@/content/topics/articles/sections/the.mdx'),
    zero: () => import('@/content/topics/articles/sections/zero.mdx'),
    uncountable: () => import('@/content/topics/articles/sections/uncountable.mdx'),
    eaters: () => import('@/content/topics/articles/sections/eaters.mdx'),
    names: () => import('@/content/topics/articles/sections/names.mdx'),
    fixed: () => import('@/content/topics/articles/sections/fixed.mdx'),
    comparison: () => import('@/content/topics/articles/sections/comparison.mdx'),
    stories: () => import('@/content/topics/articles/sections/stories.mdx'),
    translation: () => import('@/content/topics/articles/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/articles/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/articles/sections/decision.mdx'),
    exercises: () => import('@/content/topics/articles/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/articles/sections/quiz.mdx'),
    history: () => import('@/content/topics/articles/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/articles/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/articles/sections/plan.mdx'),
  },
  prepositions: {
    idea: () => import('@/content/topics/prepositions/sections/idea.mdx'),
    'time-at-in-on': () => import('@/content/topics/prepositions/sections/time-at-in-on.mdx'),
    'place-at-in-on': () => import('@/content/topics/prepositions/sections/place-at-in-on.mdx'),
    'place-relations': () => import('@/content/topics/prepositions/sections/place-relations.mdx'),
    movement: () => import('@/content/topics/prepositions/sections/movement.mdx'),
    'time-duration': () => import('@/content/topics/prepositions/sections/time-duration.mdx'),
    'verb-prep': () => import('@/content/topics/prepositions/sections/verb-prep.mdx'),
    'adj-prep': () => import('@/content/topics/prepositions/sections/adj-prep.mdx'),
    'noun-prep': () => import('@/content/topics/prepositions/sections/noun-prep.mdx'),
    comparison: () => import('@/content/topics/prepositions/sections/comparison.mdx'),
    stories: () => import('@/content/topics/prepositions/sections/stories.mdx'),
    translation: () => import('@/content/topics/prepositions/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/prepositions/sections/mistakes.mdx'),
    decision: () => import('@/content/topics/prepositions/sections/decision.mdx'),
    exercises: () => import('@/content/topics/prepositions/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/prepositions/sections/quiz.mdx'),
    history: () => import('@/content/topics/prepositions/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/prepositions/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/prepositions/sections/plan.mdx'),
  },
  'phrasal-verbs': {
    idea: () => import('@/content/topics/phrasal-verbs/sections/idea.mdx'),
    types: () => import('@/content/topics/phrasal-verbs/sections/types.mdx'),
    placement: () => import('@/content/topics/phrasal-verbs/sections/placement.mdx'),
    'particles-up-down-out': () =>
      import('@/content/topics/phrasal-verbs/sections/particles-up-down-out.mdx'),
    'particles-off-on-in': () =>
      import('@/content/topics/phrasal-verbs/sections/particles-off-on-in.mdx'),
    'particles-through-away': () =>
      import('@/content/topics/phrasal-verbs/sections/particles-through-away.mdx'),
    polysemy: () => import('@/content/topics/phrasal-verbs/sections/polysemy.mdx'),
    register: () => import('@/content/topics/phrasal-verbs/sections/register.mdx'),
    work: () => import('@/content/topics/phrasal-verbs/sections/work.mdx'),
    life: () => import('@/content/topics/phrasal-verbs/sections/life.mdx'),
    stories: () => import('@/content/topics/phrasal-verbs/sections/stories.mdx'),
    translation: () => import('@/content/topics/phrasal-verbs/sections/translation.mdx'),
    mistakes: () => import('@/content/topics/phrasal-verbs/sections/mistakes.mdx'),
    exercises: () => import('@/content/topics/phrasal-verbs/sections/exercises.mdx'),
    quiz: () => import('@/content/topics/phrasal-verbs/sections/quiz.mdx'),
    history: () => import('@/content/topics/phrasal-verbs/sections/history.mdx'),
    cheatsheet: () => import('@/content/topics/phrasal-verbs/sections/cheatsheet.mdx'),
    plan: () => import('@/content/topics/phrasal-verbs/sections/plan.mdx'),
  },
};

export function hasContent(slug: string): boolean {
  return slug in SECTION_CONTENT;
}

export function sectionLoader(topicSlug: string, sectionSlug: string): ContentLoader | undefined {
  return SECTION_CONTENT[topicSlug]?.[sectionSlug];
}
